# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: shivknp
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: testapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sls002-httpapi-nodejs-aws

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

functions:
  createAuction:
    handler: handler.createAuction
    events:
      - httpApi:
          path: /
          method: post
